image: registry.windmaker.net:5005/a-castellano/limani/base:202104052102

stages:
    - test


tests:
  stage: test
  before_script:
    - apt-get update
    - apt-get -y install libdatetime-format-iso8601-perl libemail-abstract-perl libnet-http-perl libjson-types-perl libcpanel-json-xs-perl libio-all-lwp-perl libmoose-perl libmoosex-semiaffordanceaccessor-perl libmoosex-strictconstructor-perl libmoosex-types-common-perl libconfig-json-perl libjson-any-perl libjson-perl libdate-calc-perl libboolean-perl libmoosex-types-email-perl libjson-parse-perl
    - apt-get install -y libtest-more-utf8-perl libtest-class-perl libtest-mockmodule-perl
    - perl Makefile.PL
    - make
    - mutator mutate lib/Toggl/Wrapper.pm
    - mutator mutate lib/Toggl/Wrapper/TimeEntry.pm
    - cpanm Devel::Mutator
  script:
    - make test
    - mutator test

