image: registry.windmaker.net:5005/a-castellano/limani/base

stages:
  - test
  - coverage
  - build
  - repo

tests:
  stage: test
  before_script:
    - export TZ=Europe/Madrid
    - ln -snf /usr/share/zoneinfo/$TZ /etc/localtime
    - echo $TZ > /etc/timezone
    - apt-get update
    - apt-get -y install libdatetime-format-iso8601-perl libemail-abstract-perl libnet-http-perl libjson-types-perl libcpanel-json-xs-perl libio-all-lwp-perl libmoose-perl libmoosex-semiaffordanceaccessor-perl libmoosex-strictconstructor-perl libmoosex-types-common-perl libconfig-json-perl libjson-any-perl libjson-perl libdate-calc-perl libboolean-perl libmoosex-types-email-perl libjson-parse-perl
    - apt-get install -y libtest-more-utf8-perl libtest-class-perl libtest-mockmodule-perl make cpanminus libppi-perl libtest-most-perl libextutils-installpaths-perl libmodule-build-tiny-perl libclass-accessor-class-perl libclass-accessor-lite-perl libtest-fatal-perl
    - cpanm Devel::Mutator
    - perl Makefile.PL
    - make
    - mutator mutate lib/Toggl/Wrapper.pm
    - mutator mutate lib/Toggl/Wrapper/TimeEntry.pm
  script:
    - make test
    - mutator test

coverage:
  stage: coverage
  before_script:
    - export TZ=Europe/Madrid
    - ln -snf /usr/share/zoneinfo/$TZ /etc/localtime
    - echo $TZ > /etc/timezone
    - apt-get update
    - apt-get -y install libdatetime-format-iso8601-perl libemail-abstract-perl libnet-http-perl libjson-types-perl libcpanel-json-xs-perl libio-all-lwp-perl libmoose-perl libmoosex-semiaffordanceaccessor-perl libmoosex-strictconstructor-perl libmoosex-types-common-perl libconfig-json-perl libjson-any-perl libjson-perl libdate-calc-perl libboolean-perl libmoosex-types-email-perl libjson-parse-perl
    - apt-get install -y libtest-more-utf8-perl libtest-class-perl libtest-mockmodule-perl make cpanminus libppi-perl libtest-most-perl libextutils-installpaths-perl libmodule-build-tiny-perl libclass-accessor-class-perl libclass-accessor-lite-perl libtest-fatal-perl libdevel-cover-perl
    - cpanm Devel::Mutator
    - perl Makefile.PL
    - make
    - mutator mutate lib/Toggl/Wrapper.pm
    - mutator mutate lib/Toggl/Wrapper/TimeEntry.pm
  script:
    - make test
    - mutator test
    - cover -test
  coverage: /Total\s+.+\s(\d+\.\d+?)$/

package:
  stage: build
  artifacts:
    paths:
      - build/*
  before_script:
    - export TZ=Europe/Madrid
    - ln -snf /usr/share/zoneinfo/$TZ /etc/localtime
    - echo $TZ > /etc/timezone
    - apt-get update
    - apt-get install -y dh-make-perl dpkg-dev
    - apt-get -y install libdatetime-format-iso8601-perl libemail-abstract-perl libnet-http-perl libjson-types-perl libcpanel-json-xs-perl libio-all-lwp-perl libmoose-perl libmoosex-semiaffordanceaccessor-perl libmoosex-strictconstructor-perl libmoosex-types-common-perl libconfig-json-perl libjson-any-perl libjson-perl libdate-calc-perl libboolean-perl libmoosex-types-email-perl libjson-parse-perl
    - apt-get install -y libtest-more-utf8-perl libtest-class-perl libtest-mockmodule-perl make cpanminus libppi-perl libtest-most-perl libextutils-installpaths-perl libmodule-build-tiny-perl libclass-accessor-class-perl libclass-accessor-lite-perl libtest-fatal-perl libdevel-cover-perl
  script:
    - export DEBEMAIL="alvaro.castellano.vela@gmail.com"
    - export DEBFULLNAME="Álvaro Castellano Vela"
    - dpkg-buildpackage -uc -b
    - mkdir build
    - mv ../*.deb build/

upload_package_to_repo:
  stage: repo
  image: registry.windmaker.net:5005/a-castellano/limani/base_curl:202104052102
  script:
    - SNAPSHOTDATE=$(date +%G%m%d%k%M%S)
    - PACKAGE=$(ls build)
    - echo ${PACKAGE}
    - curl -X POST -F file=@build/$PACKAGE http://packages.windmaker.net:8000/api/files/libtoggl-wrapper-perl || exit 1
    - curl -X POST http://packages.windmaker.net:8000/api/repos/packages-windmaker-focal/file/libtoggl-wrapper-perl || exit 1
    - "curl -X PUT -H 'Content-Type: application/json' http://packages.windmaker.net:8000/api/publish/:./focal --data '{}' || exit 1"
  dependencies:
    - package
  only:
    - /^v.*$/
