language: perl
perl:
  - "5.24"
  - "5.22"
  - "5.20"

script: 'perl Makefile.PL ; make ; mutator mutate lib/Toggl/Wrapper.pm; make test &&mutator test'

after_success:
  - cover -test
  - cover -report codecov
